#!/usr/bin/env bash
# Install your load balancer
sudo apt install -y haproxy=1.5\*
file=/etc/haproxy/haproxy.cfg
sudo echo -e "frontend haproxynode
\tbind *:80
\tmode http
\tdefault_backend nodes" | sudo tee -a $file
sudo echo -e "backend nodes
\tmode http
\tbalance roundrobin
\toption forwardfor
\thttp-request set-header X-Forwarded-Port %[dst_port]
\tserver 447634-web-01 54.87.157.81:80 check
\tserver 447634-web-02 35.153.231.17:80 check" | sudo tee -a $file
sudo service haproxy restart
